### ISSUE TITLE
[Request] Update to last version

### ISSUE THREAD

**Issue by InventM4n** [portapps/beaker-browser-portable#9]
Would you update it to version 1 beta 4? https://beakerbrowser.com/2020/06/04/beaker-1-0-beta-4.html

Thanks a lot

**Comment by crazy-max** [comment]
@InventM4n We are aware of and notified of new application updates. So there's no need to create an issue to update an application. Thanks for your understanding.

**Comment by ioc2e3** [comment]
It’s already 2025 year ...

.
